"""Write each language package's compiled grammar down as Almide source.

The grammar value in src/packages is the source of truth; this compiles it once
and records the arena, so a run does not have to. --check regenerates and fails
if what is committed no longer matches the grammar.
"""
from pathlib import Path
import argparse,json,os,shutil,subprocess,sys,tempfile

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'src/packages/tables'
FIELDS = ['ops','kids','spelling','spelling_start','spelling_end','bucket_at','bucket_next',
          'lit_mask','head_kinds','head_mask','head_start','head_len','head_run','kind_of']

ap = argparse.ArgumentParser(description=__doc__)
ap.add_argument('--check', action='store_true', help='fail if the committed tables are not what the grammar compiles to')
args = ap.parse_args()

def dump():
    with tempfile.TemporaryDirectory() as tmp:
        project = Path(tmp)
        shutil.copytree(ROOT / 'src', project / 'src',
                        ignore=shutil.ignore_patterns('main.almd', 'lang.almd', 'tables', 'tables.almd'))
        shutil.copyfile(ROOT / 'scripts/grammar_tables_probe.almd', project / 'src/main.almd')
        (project / 'almide.toml').write_text('[package]\nname = "grammar_tables"\nversion = "0.1.0"\nedition = "2026"\n')
        binary = project / 'probe'
        subprocess.run([os.environ.get('ALMIDE_BIN', 'almide'), 'build', '-o', str(binary)], cwd=project, check=True)
        return json.loads(subprocess.check_output([str(binary)], text=True))

def wrap(prefix, parts, width=100):
    lines, line = [], prefix
    for i, part in enumerate(parts):
        piece = part + (',' if i + 1 < len(parts) else '')
        if len(line) + len(piece) > width and line != prefix:
            lines.append(line)
            line = '  ' + piece
        else:
            line += piece
    lines.append(line)
    return '\n'.join(lines)

def module(pkg):
    head = (f'// Generated by scripts/gen_grammar_tables.py from the {pkg["id"]} package\'s grammar.\n'
            '// Do not edit: `python3 scripts/gen_grammar_tables.py` writes it and\n'
            '// `--check` fails the build when the grammar and this file disagree.\n'
            'import self.parser\n\n')
    body = []
    for name in FIELDS:
        body.append(wrap(f'fn {name}() -> List[Int] = [', [str(v) for v in pkg[name]]) + ']')
    body.append(wrap('fn texts() -> List[String] = [', [json.dumps(t, ensure_ascii=False) for t in pkg['texts']]) + ']')
    body.append('fn tables() -> parser.Tables = parser.Tables {\n'
                + ''.join(f'  {name}: {name}(),\n' for name in FIELDS)
                + '  texts: texts(),\n'
                + f'  start: {pkg["start"]},\n  extra: {pkg["extra"]},\n' + '}')
    body.append('fn compiled() -> parser.Compiled = parser.from_tables(tables())')
    return head + '\n'.join(body) + '\n'

def dispatcher(ids):
    return ('// Generated by scripts/gen_grammar_tables.py.\n'
            '// Every package that ships a compiled grammar, by package id.\n'
            + ''.join(f'import self.packages.tables.{i} as table_{i}\n' for i in ids)
            + 'import self.parser\n\n'
            'fn compiled_for(id: String) -> Option[parser.Compiled] =\n  '
            + '\n  else '.join(f'if id == "{i}" then some(table_{i}.compiled())' for i in ids)
            + '\n  else none\n')

packages = dump()
ids = [p['id'] for p in packages]
written = {f'{p["id"]}.almd': module(p) for p in packages}
written['../tables.almd'] = dispatcher(ids)

if args.check:
    bad = [name for name, text in written.items() if not (OUT / name).exists() or (OUT / name).read_text() != text]
    if bad:
        print('grammar tables are stale: ' + ', '.join(sorted(bad)) + '\n'
              'run: python3 scripts/gen_grammar_tables.py', file=sys.stderr)
        sys.exit(1)
    print(f'Grammar tables: {len(ids)} package(s) match what their grammar compiles to')
else:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, text in written.items():
        (OUT / name).write_text(text)
    print(f'Grammar tables: wrote {len(ids)} package(s) ' + ', '.join(ids))
